networks:
  server:
    driver: bridge
services:
  php-fpm:
    build: ./docker/php-fpm
    working_dir: /var/www/
    environment:
      PHP_IDE_CONFIG: serverName=default
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - server
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    environment:
      PHP_IDE_CONFIG: serverName=default
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - server
    depends_on:
      - php-fpm
  postgres-db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=postgres
    networks:
      - server